# 更多规则使用说明请参考 http://AppOpt.suto.top

# 安装后点击模块操作按钮，会根据 confige.txt 中的 8G3 和 mode 自动下载规则并原样写入本文件。
# AkiAppOpt 支持数字范围以及 e-core / p-core / hp-core / all-core。

# 传统写法示例：
# com.android.systemui{RenderThread}=hp-core

# 块写法示例：
# com.android.systemui {
#     RenderThread=hp-core
#     binder:*=e-core,p-core
# }
